name: Deploy to Server

on:
  push:
    branches:
      - deploytest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Add host
      run: |
        ssh-keyscan zenful.cloud > ~/.ssh/known_hosts

    - name: Set up Docker Compose
      run: |
        # Install Docker Compose
        curl -L "https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Run Docker Compose
      run: |
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DOCKER_HOST=ssh://deploytest@zenful.cloud docker-compose -f ./compose.prod.yaml up -d

    # - name: Copy over the docker compose file
    #   run: |
    #     scp -o StrictHostKeyChecking=no compose.prod.yaml deploytest@zenful.cloud:guestbook/compose.yaml
    # - name: Deploy code via SSH
    #   run: |
    #     ssh -o StrictHostKeyChecking=no deploytest@zenful.cloud "cd guestbook && docker compose up -d"
